name: flutterwarden
description: A flutter client for Bitwarden password manager.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  ant_icons: ^1.0.0
  cached_network_image: ^2.2.0+1
  expandable: ^4.1.4

  # Dependency Injection
  get_it: ^4.0.4
  injectable: ^1.0.2

  # State management
  bloc: ^4.0.0
  flutter_bloc: ^4.0.0

  # Dart data class
  json_serializable: ^3.3.0
  freezed_annotation: ^0.11.0

  # Network
  data_connection_checker: ^0.3.4
  url_launcher: ^5.5.0
  http: ^0.12.2

  # Local cache
  hive: ^1.4.2

  # Cryptography
  pointycastle: ^1.0.2
  encrypt: ^4.0.2

  # Routing
  auto_route: ^0.6.6

  # Logging
  logger: ^0.9.2

  # Fingerprint authentication
  local_auth: ^0.6.2+3

  # Misc
  dartz: ^0.9.1
  rxdart: ^0.24.1
  path_provider: ^1.6.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generators
  freezed: ^0.11.4
  build_runner: ^1.10.0
  auto_route_generator: ^0.6.6
  injectable_generator: ^1.0.2

  # Linting
  effective_dart: ^1.2.4

  # Testing
  bloc_test: ^5.0.0
  mockito: ^4.1.1

flutter:
  uses-material-design: true
